### PR TITLE
Wildcard support added

### PR DESCRIPTION
**Pull request by dralisz82**
Hi Patrick,

I've just implemented some improvements on your already awesome library:

Now supporting a single occurrence of a wildcard in subscriptions
A topic argument is introduced in subscription callback prototype, hence it is a non-backward compatible change

Feel free to pull (and adapt) these changes into your repository.

BR,
Szilárd

### CODE REVIEW

**Comment by plapointe6** [comment]
I like your implementation. The only thing is preventing me to merge your changes right now is the non-backward compatible change it brings. However, I have a suggestion to make these changes backward compatible : overloading the `subscribe` method to add the possibility to either pass a callback that accept the topic and the message or only a message.

You could do this in `EspMQTTClient.h` : 
```c++
typedef void(*MessageReceivedCallback) (const String &message); // The original
typedef void(*MessageReceivedCallbackWithTopic) (const String &message, const String &topic); // The new that support wildcards
```
```c++
  // The callback that will not be null will be the one that will be called.
  struct TopicSubscriptionRecord {
    String topic;
    MessageReceivedCallback callback;
    MessageReceivedCallbackWithTopic callbackWithTopic;
  };
```
```c++
bool subscribe(const String &topic, MessageReceivedCallback messageReceivedCallback); // Keep the original one as is
bool subscribe(const String &topic, MessageReceivedCallbackWithTopic messageReceivedCallback); // Add this one 
```

in `EspMQTTClient.cpp` : 
- Handle the overwirting of the subscribe function and avoid as much repetition of code as possible. 
- Set either callbackWithTopic or callback depending of wich `subscribe`function has been called.
- When a message is received, call the callback that is not equal to null in the Subscription Record.

If you don't want to do these changes, I could do them by myself.

**Comment by dralisz82** [comment]
Thanks for the feedback and for the suggestions!

I like your proposed solution, and was thinking on a similar approach, but had no time to work on it.
In the coming days I'll have some time to implement this improvement and do some testing, so I can do it. If I don't succeed on this week, I'll let you grab the opportunity to implement this. ;)

Thanks!

BR,
Szilárd

**Comment by dralisz82** [comment]
Hi Patrick,

I've managed to restore backward compatibility with zero lines of duplicated code! :)
See my second commit for details. I've tested and it works fine.
I've pulled in your suggestions to the code, and built my solution around them.

BR,
Szilárd

**Comment by plapointe6** [comment]
Great ! Will be merged soon and will be included in the 1.8.0 release.

**Pull request merged**
