### PR TITLE
Fixed reconnection bug

### PR DESCRIPTION
**Pull request by abqmichael**
This fix adds an optional network (WiFi) and client (MQTTT) connection algorithm in EspMQTTClient::loop(). By add, I mean that it puts the new code/algorithm behind a #ifdef WIFI_FIX blocks so that the person testing the code can switch between the new and old algorithms.

The new algorithm uses a state machine formulation as opposed to the prior condition-styled algorithm. The state machine moves through six states that are documented in the comments in EspMQTTClient::loop().

Fix developed by Michael McDonald of Albuquerque NM.

### CODE REVIEW

**Comment by plapointe6** [comment]
I created a branch for this pull request [here](https://github.com/plapointe6/EspMQTTClient/tree/dev-abqmichael-fix). I removed all #ifdef clauses and corrected some indentation issues to the changes you published here. Also, I corrected all conflict that was introduced since last library updates. Now, I will be able to start the review of theses changes. Keep an eye to the commits of the branch to keep track of the progress.

**Comment by plapointe6** [comment]
I have some question : 

1- I see that you added a `mBrokerConnectPauseMills` member. It is set to 60 seconds by default. I also see that you will wait this delay before reconnecting to the broker after a connection lost. Can you explain why you applied this logic ? Do reconnecting instantly to the broker right after the wifi connection as been established cause instability with ESP32 ?

2- What's exactly the purpose of `mWaitCount` ? I see that it is used for different print, but I have difficulty to see why you make different prints depending of his value. Exemple, : 
```c++
      if (mEnableSerialLogs) {
        if (mWaitCount == 0) 
        {
          Serial.printf("WiFi starting, MQTT down, waiting %d ", mWaitCount);
        }
        else if (mWaitCount % 1000 == 0) 
        {
          Serial.printf("\nWiFi starting, MQTT down, waiting %d ", mWaitCount);
        }
        else if (mWaitCount < 11) 
        {
          Serial.printf("%d, ", mWaitCount);
        }
        else if (mWaitCount % 50 == 0) 
        {
          Serial.printf(".");
        }
      }
      delay(10);
      mWaitCount++;
```
Not sure why you made these complicated conditions to print something like "Connecting to WiFi ..."

3- Any other information about your fix would be welcome. I am trying to find what made ESP32 connection unstable in my old code and what make it more stable in the new fix.

Thank you

**Comment by abqmichael** [comment]
Great to hear you’re on it. 

I hope the following makes sense for explaining the issue. It’s a simple and complicated thing:

The mBrokerConnectPauseMills is to give your application a limited opportunity to do some work while it’s waiting for a reconnect. Specifically, mMqttClient.connect (used in connectToMqttBroker) is a blocking method that will wait for either a connection (usually fast) or until the connection attempt times out (usually a long time). This is much different than the wifi connect stuff. 

When the code reaches state 3, it calls connectToMqttBroker on every loop before it executes any work functions (e.g., runs the delayed execution list). Without the pause, this means that if the MQTT server is down, it would call connectToMqttBroker, wait until the mMqttClient.connect request timed out, then call all the methods on the delayed execution list, then repeat. That would be OK in applications that have no use beyond the MQTT interface.  For me, only giving my app that small amount of work effectively put my device offline when the server was down. Lights wouldn’t animate. Sensors wouldn’t get serviced. 

Because I didn’t see a non-blocking mMqttClient.connect (as other MQTT libraries have), I decided to leave the logic of state 3 alone and implement a way for connectToMqttBroker to give my application some breathing room between mMqttClient.connect attempts. So mBrokerConnectPauseMills limits the frequency that the library actually calls mMqttClient.connect. The variable has the code bypassing the call to mMqttClient.connect whenever connectToMqttBroker is called too close to the last time mMqttClient.connect was called.


The mWaitCount variable was mainly for my debugging, especially in early development but I find it very comforting. Specifically, it allows the system to generate reasonable status messages as the system is connecting without overwhelming the user. It is especially nice when watching the WiFi connection get made. The code below first generates a message about the wifi starting up and then it prints a number (1 2 3 4 .. 10) and then a few dots as it waits. This message set repeats then repeats in a similar form while the app works at trying to get the connection made. 

So what the library user/app developer sees is a sort of message that slowly evolves saying “yes, I’m in there trying to connect to wifi.” Then if they monitor the system through different reboots or reconnection attempts, they also have a nice visual way to compare how long each connection attempt took to make.

Michael

**Comment by Sabidos** [comment]
Good evening,

Friends,

I really liked your library, well written, but this problem is making me sleepy, is there a way to make this correction in another way, since the library maintainer does not do the unification?

I am very grateful for any help!

**Comment by abqmichael** [comment]
I don’t control the repository. However, when I click on the link that says from abqmichaelj:master, it brings me to the code I checked in. You can download that and get what I’m using and at least the bug will be resolved. I’ll try and look into this tomorrow.

**Comment by Sabidos** [comment]
Thank you,

I managed to replace the files of the original Repository and I'm testing it ... I'll leave it running for the whole day so when later I get home from work do some reconnection tests, but I already noticed some improvements when calling, he doesn't keep giving me a message of Wifi INIT, then I'll look at why it takes to connect to MQTT.

`iFi and MQTT down: starting WiFi

WiFi: Connecting to CachorroBravo ... 
WiFi starting, MQTT down, waiting 0 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, ...
WiFi up, MQTT down. IP = 192.168.1.45
WEB: Updater ready, open http://TestClient.local in your browser and login with username 'admin' and password '***'.
WiFi up, MQTT starting
MQTT: Connecting to broker @192.168.1.200 ... unable to connect, MQTT_CONNECT_FAILED
WiFi up, MQTT starting

WiFi up, MQTT starting .................................................
WiFi up, MQTT starting .................................................
WiFi up, MQTT starting .................................................
WiFi up, MQTT starting .................................................
WiFi up, MQTT starting .................................................
WiFi up, MQTT starting ...........................................MQTT: Connecting to broker @192.168.1.200 ... ok.
MQTT: Subscribed to [hb/set/jorge/quarto/luz]
MQTT: Subscribed to [hb/set/jorge/banheiro/luz]
WiFi up, MQTT up after multiple tries.
MQTT >> [hb/set/jorge/quarto/luz] 0
0
MQTT << [hb/get/jorge/quarto/luz] 0
MQTT >> [hb/set/jorge/banheiro/luz] 0
0
MQTT << [hb/get/jorge/banheiro/luz] 0
Debouncer fell
Pressionado: BTN02
MQTT << [hb/get/jorge/quarto/luz] 1
Debouncer fell
Pressionado: BTN02
MQTT << [hb/get/jorge/quarto/luz] 0
Debouncer fell
Pressionado: BTN01
MQTT << [hb/get/jorge/banheiro/luz] 1
`

**Comment by abqmichael** [comment]
Great to hear that. Still haven’t gotten to the repository. Git is not my thing and I didn’t realize that the repository owner (plapointe6) wanted me to remove that part in the patch before he would integrate/accept the changes in the main branch. I’ve been running exactly what you now have for 3 months and haven’t had a problem with this part of the code. For your testing, I recommend seeing what happens when you alternatively restart your MQTT server, your network router (wifi bridge), or both. This is quite an improvement.

From your printout, I see you’re getting the advantage of the code I put in to make the reporting manageable. Instead of printing "WiFi up, MQTT starting" on a regular interval, the code prints dots at a slow interval. I sort of timed that so you would be able to sort of gauge how long it takes to connect.  It’s cool to see it doing the same for you.

Michael

**Comment by abqmichael** [comment]
plapointe6: Could you give us an update on the status of the patch I provided and whether you need me to do anything? GitHub shows that that there's a conflict on this branch that needs to be resolved. I'm guessing that was a conflict when you merged your unpublished version with mine as the version with the conflicts still has most of the #ifdef WIFI_FIX lines so it's probably a dead issue. I also see that there's a branch called dev-abqmichael-fix that has all those #ifdefs removed. That looks like the right one to use.

As you can see from Sabidos' comments, there is at least one other developer who had the same problem I encountered. Happily, he is using corrected code but possibly the version I posted. Better would be the branch at https://github.com/plapointe6/EspMQTTClient/tree/dev-abqmichael-fix. 

Looking at the timing of this all, I am guessing that world history caught up with your development and your work is on a pause. It is certainly a very difficult time everywhere. I hope you are well, that this crisis resolves well for you, and that your work can continue soon. Until then, keep safe.

Michael McDonald
Albuquerque, NM

> I created a branch for this pull request [here](https://github.com/plapointe6/EspMQTTClient/tree/dev-abqmichael-fix). I removed all #ifdef clauses and corrected some indentation issues to the changes you published here. Also, I corrected all conflict that was introduced since last library updates. Now, I will be able to start the review of theses changes. Keep an eye to the commits of the branch to keep track of the progress.

**Comment by plapointe6** [comment]
Hello @abqmichael,

The current situation keep me from working on this lib for now, but I understand that it's a frustating issue for many peoples.

You are right, the branch dev-abqmichael-fix is the fix ready for merge. As so, all the #ifdef as been removed and all conflict has been resolved. I also corrected some minor stuff.
So, If you want to use this fix, it is ok to use this branch.

For the branch dev, it is a work in progress and I don't recommand using it for now. The branch is a big update to the library that implements your connection/disconnection mechanics in another way while adding some other requested functionnalities. I made that because I was planning to switch to an unblocking MQTT client library in the future (An higly requested improvment) and the reformatted connection mechanics would handle it.

When things wil calm down for me I will dive into this with more update and testing.

Thank you.

**Comment by abqmichael** [comment]
Thank you for the update Patrick. I’m glad I wasn’t unknowingly holding back progress. 

This is certainly a tough time for making progress on many fronts. It is encouraging that the effort is still on your mind and that you are even working to make something significantly better. I look forward to seeing what you’re doing.

**Comment by plapointe6** [comment]
Hello, I finally came back to home, so I was able to do some basic tests/correction to my code from `dev` branch that I begun before COVID.

Now, this is merged to master, but I is not releashed yet. I am doing some testing and I will put this into v1.9 soon.

I don't use ESP32. I have some boards for testing, but I use ESP8266 for my whole smart home setup. If you can test if the current `master` code is stable on your ESP32 it would be great. Thanks.

**Pull request closed without merging**
