### PR TITLE
added primitive publish helper functions + mqtt getters

### PR DESCRIPTION
**Pull request by hixfield**
I've been using this library for some time now.
My PR includes:

I included primitive publish helper functions so that the user's of the lib does not need to cast the published topic everytime to a String(). This makes the code more readable.

Getters for MQTT client name, port and server ip (when creating derived classes these are useful; I need them anyway)

### CODE REVIEW

**Comment by plapointe6** [comment]
I like the idea of the getters and setters. However, for the overloading for the primitives types, I am not sure that it is the best way to do it. A better implmentation of this could use c++ templates to avoid overloading the publish function too much. Are youy willing to test if it could work with templates ?

**Comment by hixfield** [comment]
Never used templates that much but willing to try it. Can you offer a suggestion to get me started?

**Comment by hixfield** [comment]
Found a good tutorial http://www.cplusplus.com/doc/oldtutorial/templates/ will have a look at it and will post update to PR!

**Comment by plapointe6** [comment]
Let me know if you need help.

**Comment by StephanMeijer** [comment]
Looks sweet.

**Comment by plapointe6** [comment]
Merged into master and will be part of v1.9, thanks.

**Pull request closed without merging**
